name: CI
on: [push, pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  checks:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - run: npm ci --ignore-scripts
      - run: npm run prettier:check
      - run: npm run lint:check
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*', 'current']
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Setting up Node.js (v${{ matrix.node-version }}.x)
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run test:ci
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - run: npm ci --ignore-scripts
      - run: npm run build:esm
      - run: npm run build:cjs
      - run: npm run build:types
      - run: npm run check:cjs
      - run: npm run check:esm
